chill_main:
   resource: "@ChillMainBundle/Resources/config/routing.yml"

#TODO this part should be modified, see https://redmine.champs-libres.coop/issues/273

#load routes for custom fields
cl_custom_fields:
   resource: .
   type: chill_routes
   
#load route for persons
chill_person:
    resource: .
    type: chill_routes_person
