security:
    providers:
        chain_provider:
            chain :
                providers: [in_memory, users]
        in_memory:
            memory:
                users:
                    admin: { password: "%admin_password%", roles: 'ROLE_ADMIN' }
        users:
            entity:
                class: Chill\MainBundle\Entity\User
                property: username

    encoders:
        Chill\MainBundle\Entity\User: 
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                csrf_parameter: _csrf_token
                intention: authenticate
                csrf_provider: form.csrf_provider
            logout: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # access for homepage, the homepage redirect admin to admin section
        - { path: ^/$, roles: [ROLE_USER, ROLE_ADMIN] }
        # idem
        - { path: ^/([a-z]+/)?homepage, roles: [ROLE_USER, ROLE_ADMIN] }
        # admin section, only for admin
        - { path: ^/([a-z]+/)?admin, roles: ROLE_ADMIN }
        # other pages, only for regular user (no admin)
        - { path: ^/, roles: ROLE_USER }
